# Default
title: ""                       # Website title
description: ""                 # Website description
keywords: ""                    # Website keywords
logo: "/assets/images/logo.png" # Website logo
author: ""                      # Website author
url: ""                         # Website

gw_verify: "" # google webmaster verification
ga_verify: "" # google analytics
disqus_name: "" # disqus username (comments)

# Where things are
source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes
collections:
  posts:
    output:     true
    permalink:  :categories/:title.html

# Handling Reading
safe:                 false
include:              [".htaccess"]
exclude:              ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files:           [".git", ".svn"]
encoding:             "utf-8"
markdown_ext:         "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
plugins_dir:   []

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Serving
//detach:  false
//port:    4000
//host:    127.0.0.1
//baseurl: "" # does not include hostname
//show_dir_listing: false

# Outputting
permalink:     date
paginate: 6
paginate_path: /page/:num/
timezone:      null

quiet:    false
verbose:  false
defaults: []

liquid:
  error_mode: warn

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

gems:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap